// <auto-generated />
using System;
using Flexfit.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flexfit.Migrations
{
    [DbContext(typeof(FlexFitDbContext))]
    [Migration("20260603090459_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BranchAmenityMapping", b =>
                {
                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BranchId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("BranchAmenityMappings", (string)null);
                });

            modelBuilder.Entity("Flexfit.Models.Branch", b =>
                {
                    b.Property<Guid>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreditCost")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BranchId")
                        .HasName("PK__Branches__A1682FC57F628C8E");

                    b.HasIndex("GymId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Flexfit.Models.BranchImage", b =>
                {
                    b.Property<Guid>("BranchImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchImageId")
                        .HasName("PK__BranchIm__DEDBCB2E0DD9038B");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchImages");
                });

            modelBuilder.Entity("Flexfit.Models.BranchStaff", b =>
                {
                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("StaffId", "BranchId");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchStaffs");
                });

            modelBuilder.Entity("Flexfit.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0BC8C5ABA1");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__Categori__8517B2E053ED6742")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Flexfit.Models.CheckInLog", b =>
                {
                    b.Property<Guid>("CheckInLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("ClassBookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GymBookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ScannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("ScannedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CheckInLogId")
                        .HasName("PK__CheckInL__D713C446CD31F49B");

                    b.HasIndex("ClassBookingId");

                    b.HasIndex("GymBookingId");

                    b.HasIndex("ScannedBy");

                    b.HasIndex("UserId");

                    b.ToTable("CheckInLogs");
                });

            modelBuilder.Entity("Flexfit.Models.Class", b =>
                {
                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CaloriesBurnEstimate")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CoachName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreditCost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Open");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__CB1927C00781F387");

                    b.HasIndex("BranchId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Flexfit.Models.ClassBooking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("BookedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckInStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("NotCheckedIn");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CheckedInBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreditUsed")
                        .HasColumnType("int");

                    b.Property<bool>("IsReminded1h")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReminded3h")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("QrExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QrToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RefundCredit")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Booked");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookingId")
                        .HasName("PK__ClassBoo__73951AEDEA9CD5B7");

                    b.HasIndex("CheckedInBy");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "BookingCode" }, "UQ__ClassBoo__C6E56BD580D57C58")
                        .IsUnique();

                    b.ToTable("ClassBookings");
                });

            modelBuilder.Entity("Flexfit.Models.ClassSchedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndHour")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartHour")
                        .HasColumnType("time");

                    b.HasKey("ScheduleId")
                        .HasName("PK__ClassSch__9C8A5B49CB2537F1");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassSchedules");
                });

            modelBuilder.Entity("Flexfit.Models.CreditPackage", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("BonusCredit")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreditAmount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PackageId")
                        .HasName("PK__CreditPa__322035CC8FA60D13");

                    b.ToTable("CreditPackages");
                });

            modelBuilder.Entity("Flexfit.Models.CreditTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<int>("BalanceBefore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionId")
                        .HasName("PK__CreditTr__55433A6B7CD8E897");

                    b.HasIndex("UserId");

                    b.ToTable("CreditTransactions");
                });

            modelBuilder.Entity("Flexfit.Models.FavoriteClass", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("FavoriteClasses", (string)null);
                });

            modelBuilder.Entity("Flexfit.Models.FavoriteGym", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "GymId");

                    b.HasIndex("GymId");

                    b.ToTable("FavoriteGyms");
                });

            modelBuilder.Entity("Flexfit.Models.Gym", b =>
                {
                    b.Property<Guid>("GymId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GymName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GymId")
                        .HasName("PK__Gyms__1A3A7C967D8AF47B");

                    b.HasIndex("OwnerId");

                    b.ToTable("Gyms");
                });

            modelBuilder.Entity("Flexfit.Models.GymAmenity", b =>
                {
                    b.Property<Guid>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AmenityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AmenityId")
                        .HasName("PK__GymAmeni__842AF50BF3A9D836");

                    b.HasIndex(new[] { "AmenityName" }, "UQ__GymAmeni__7B4A459F1F1C7085")
                        .IsUnique();

                    b.ToTable("GymAmenities");
                });

            modelBuilder.Entity("Flexfit.Models.GymBooking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("BookedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckInStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("NotCheckedIn");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CheckedInBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreditUsed")
                        .HasColumnType("int");

                    b.Property<bool>("IsReminded1h")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReminded3h")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("QrExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QrToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RefundCredit")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Booked");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookingId")
                        .HasName("PK__GymBooki__73951AED2EDE095B");

                    b.HasIndex("CheckedInBy");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "BookingCode" }, "UQ__GymBooki__C6E56BD5C111A3CB")
                        .IsUnique();

                    b.ToTable("GymBookings");
                });

            modelBuilder.Entity("Flexfit.Models.GymImage", b =>
                {
                    b.Property<Guid>("GymImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GymImageId")
                        .HasName("PK__GymImage__659DCAAE6F641A53");

                    b.HasIndex("GymId");

                    b.ToTable("GymImages");
                });

            modelBuilder.Entity("Flexfit.Models.GymSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreditCost")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Open");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionId")
                        .HasName("PK__GymSessi__C9F492905AF95180");

                    b.HasIndex("BranchId");

                    b.ToTable("GymSessions");
                });

            modelBuilder.Entity("Flexfit.Models.MemberProfile", b =>
                {
                    b.Property<Guid>("MemberProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FitnessGoal")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("PreferredWorkoutTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("MemberProfileId")
                        .HasName("PK__MemberPr__0485209F89155E84");

                    b.HasIndex(new[] { "UserId" }, "UQ__MemberPr__1788CC4D526A5F60")
                        .IsUnique();

                    b.ToTable("MemberProfiles");
                });

            modelBuilder.Entity("Flexfit.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12DD7CF72D");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Flexfit.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderTransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A3832331F50");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Flexfit.Models.Promotion", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PromotionId")
                        .HasName("PK__Promotio__52C42FCF3B224CF5");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Flexfit.Models.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("ClassBookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClassBookingId");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("GymBookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GymBookingId");

                    b.Property<Guid?>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79CE5A81B34E");

                    b.HasIndex("ClassBookingId");

                    b.HasIndex("ClassId");

                    b.HasIndex("GymBookingId");

                    b.HasIndex("GymId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Flexfit.Models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1AD46A3A12");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160ACCD1031")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Flexfit.Models.SystemLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Action")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LogId")
                        .HasName("PK__SystemLo__5E548648767A2855");

                    b.HasIndex("UserId");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("Flexfit.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VerificationTokenExpires")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C75B61DB2");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053421A327A4")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Flexfit.Models.UserCredit", b =>
                {
                    b.Property<Guid>("UserCreditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("TotalEarned")
                        .HasColumnType("int");

                    b.Property<int>("TotalSpent")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserCreditId")
                        .HasName("PK__UserCred__6D8AC3E925FF6ADC");

                    b.HasIndex(new[] { "UserId" }, "UQ__UserCred__1788CC4DBC67384A")
                        .IsUnique();

                    b.ToTable("UserCredits");
                });

            modelBuilder.Entity("Flexfit.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Flexfit.Models.UserWorkoutHistory", b =>
                {
                    b.Property<Guid>("WorkoutHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("CaloriesBurned")
                        .HasColumnType("int");

                    b.Property<Guid?>("ClassBookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("GymBookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("WorkoutDurationMinutes")
                        .HasColumnType("int");

                    b.HasKey("WorkoutHistoryId")
                        .HasName("PK__UserWork__8D7C9B3DD9D92244");

                    b.HasIndex("ClassBookingId");

                    b.HasIndex("GymBookingId");

                    b.HasIndex("UserId");

                    b.ToTable("UserWorkoutHistories");
                });

            modelBuilder.Entity("BranchAmenityMapping", b =>
                {
                    b.HasOne("Flexfit.Models.GymAmenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .IsRequired()
                        .HasConstraintName("FK__BranchAme__Ameni__6E01572D");

                    b.HasOne("Flexfit.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__BranchAme__Branc__6D0D32F4");
                });

            modelBuilder.Entity("Flexfit.Models.Branch", b =>
                {
                    b.HasOne("Flexfit.Models.Gym", "Gym")
                        .WithMany("Branches")
                        .HasForeignKey("GymId")
                        .IsRequired()
                        .HasConstraintName("FK__Branches__GymId__5812160E");

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("Flexfit.Models.BranchImage", b =>
                {
                    b.HasOne("Flexfit.Models.Branch", "Branch")
                        .WithMany("BranchImages")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__BranchIma__Branc__66603565");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Flexfit.Models.BranchStaff", b =>
                {
                    b.HasOne("Flexfit.Models.Branch", "Branch")
                        .WithMany("BranchStaffs")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_BranchStaffs_Branches");

                    b.HasOne("Flexfit.Models.User", "Staff")
                        .WithMany("BranchStaffs")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_BranchStaffs_Users");

                    b.Navigation("Branch");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Flexfit.Models.CheckInLog", b =>
                {
                    b.HasOne("Flexfit.Models.ClassBooking", "ClassBooking")
                        .WithMany("CheckInLogs")
                        .HasForeignKey("ClassBookingId")
                        .HasConstraintName("FK__CheckInLo__Class__2180FB33");

                    b.HasOne("Flexfit.Models.GymBooking", "GymBooking")
                        .WithMany("CheckInLogs")
                        .HasForeignKey("GymBookingId")
                        .HasConstraintName("FK__CheckInLo__GymBo__208CD6FA");

                    b.HasOne("Flexfit.Models.User", "ScannedByNavigation")
                        .WithMany("CheckInLogScannedByNavigations")
                        .HasForeignKey("ScannedBy")
                        .IsRequired()
                        .HasConstraintName("FK__CheckInLo__Scann__22751F6C");

                    b.HasOne("Flexfit.Models.User", "User")
                        .WithMany("CheckInLogUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__CheckInLo__UserI__1F98B2C1");

                    b.Navigation("ClassBooking");

                    b.Navigation("GymBooking");

                    b.Navigation("ScannedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flexfit.Models.Class", b =>
                {
                    b.HasOne("Flexfit.Models.Branch", "Branch")
                        .WithMany("Classes")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__Classes__BranchI__7D439ABD");

                    b.HasOne("Flexfit.Models.Category", "Category")
                        .WithMany("Classes")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Classes__Categor__7E37BEF6");

                    b.Navigation("Branch");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Flexfit.Models.ClassBooking", b =>
                {
                    b.HasOne("Flexfit.Models.User", "CheckedInByNavigation")
                        .WithMany("ClassBookingCheckedInByNavigations")
                        .HasForeignKey("CheckedInBy")
                        .HasConstraintName("FK__ClassBook__Check__1AD3FDA4");

                    b.HasOne("Flexfit.Models.Class", "Class")
                        .WithMany("ClassBookings")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__ClassBook__Class__19DFD96B");

                    b.HasOne("Flexfit.Models.User", "User")
                        .WithMany("ClassBookingUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ClassBook__UserI__18EBB532");

                    b.Navigation("CheckedInByNavigation");

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flexfit.Models.ClassSchedule", b =>
                {
                    b.HasOne("Flexfit.Models.Class", "Class")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__ClassSche__Class__02084FDA");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Flexfit.Models.CreditTransaction", b =>
                {
                    b.HasOne("Flexfit.Models.User", "User")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__CreditTra__UserI__37703C52");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flexfit.Models.FavoriteClass", b =>
                {
                    b.HasOne("Flexfit.Models.Class", "Class")
                        .WithMany("FavoriteClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flexfit.Models.User", "User")
                        .WithMany("FavoriteClasses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flexfit.Models.FavoriteGym", b =>
                {
                    b.HasOne("Flexfit.Models.Gym", "Gym")
                        .WithMany("FavoriteGyms")
                        .HasForeignKey("GymId")
                        .IsRequired()
                        .HasConstraintName("FK__FavoriteG__GymId__4B7734FF");

                    b.HasOne("Flexfit.Models.User", "User")
                        .WithMany("FavoriteGyms")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__FavoriteG__UserI__4A8310C6");

                    b.Navigation("Gym");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flexfit.Models.Gym", b =>
                {
                    b.HasOne("Flexfit.Models.User", "Owner")
                        .WithMany("Gyms")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__Gyms__OwnerId__5165187F");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Flexfit.Models.GymBooking", b =>
                {
                    b.HasOne("Flexfit.Models.User", "CheckedInByNavigation")
                        .WithMany("GymBookingCheckedInByNavigations")
                        .HasForeignKey("CheckedInBy")
                        .HasConstraintName("FK__GymBookin__Check__0E6E26BF");

                    b.HasOne("Flexfit.Models.GymSession", "Session")
                        .WithMany("GymBookings")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK__GymBookin__Sessi__0D7A0286");

                    b.HasOne("Flexfit.Models.User", "User")
                        .WithMany("GymBookingUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__GymBookin__UserI__0C85DE4D");

                    b.Navigation("CheckedInByNavigation");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flexfit.Models.GymImage", b =>
                {
                    b.HasOne("Flexfit.Models.Gym", "Gym")
                        .WithMany("GymImages")
                        .HasForeignKey("GymId")
                        .IsRequired()
                        .HasConstraintName("FK__GymImages__GymId__619B8048");

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("Flexfit.Models.GymSession", b =>
                {
                    b.HasOne("Flexfit.Models.Branch", "Branch")
                        .WithMany("GymSessions")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__GymSessio__Branc__778AC167");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Flexfit.Models.MemberProfile", b =>
                {
                    b.HasOne("Flexfit.Models.User", "User")
                        .WithOne("MemberProfile")
                        .HasForeignKey("Flexfit.Models.MemberProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__MemberPro__UserI__49C3F6B7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flexfit.Models.Notification", b =>
                {
                    b.HasOne("Flexfit.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__51300E55");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flexfit.Models.Payment", b =>
                {
                    b.HasOne("Flexfit.Models.CreditPackage", "Package")
                        .WithMany("Payments")
                        .HasForeignKey("PackageId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__Packag__3E1D39E1");

                    b.HasOne("Flexfit.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__UserId__3D2915A8");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flexfit.Models.Review", b =>
                {
                    b.HasOne("Flexfit.Models.ClassBooking", "ClassBooking")
                        .WithMany()
                        .HasForeignKey("ClassBookingId")
                        .HasConstraintName("FK__Reviews__ClassBookingId");

                    b.HasOne("Flexfit.Models.Class", "Class")
                        .WithMany("Reviews")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__Reviews__ClassId__44CA3770");

                    b.HasOne("Flexfit.Models.GymBooking", "GymBooking")
                        .WithMany()
                        .HasForeignKey("GymBookingId")
                        .HasConstraintName("FK__Reviews__GymBookingId");

                    b.HasOne("Flexfit.Models.Gym", "Gym")
                        .WithMany("Reviews")
                        .HasForeignKey("GymId")
                        .HasConstraintName("FK__Reviews__GymId__43D61337");

                    b.HasOne("Flexfit.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__UserId__42E1EEFE");

                    b.Navigation("Class");

                    b.Navigation("ClassBooking");

                    b.Navigation("Gym");

                    b.Navigation("GymBooking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flexfit.Models.SystemLog", b =>
                {
                    b.HasOne("Flexfit.Models.User", "User")
                        .WithMany("SystemLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__SystemLog__UserI__625A9A57");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flexfit.Models.UserCredit", b =>
                {
                    b.HasOne("Flexfit.Models.User", "User")
                        .WithOne("UserCredit")
                        .HasForeignKey("Flexfit.Models.UserCredit", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserCredi__UserI__32AB8735");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flexfit.Models.UserRole", b =>
                {
                    b.HasOne("Flexfit.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne("Flexfit.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flexfit.Models.UserWorkoutHistory", b =>
                {
                    b.HasOne("Flexfit.Models.ClassBooking", "ClassBooking")
                        .WithMany("UserWorkoutHistories")
                        .HasForeignKey("ClassBookingId")
                        .HasConstraintName("FK__UserWorko__Class__5CA1C101");

                    b.HasOne("Flexfit.Models.GymBooking", "GymBooking")
                        .WithMany("UserWorkoutHistories")
                        .HasForeignKey("GymBookingId")
                        .HasConstraintName("FK__UserWorko__GymBo__5BAD9CC8");

                    b.HasOne("Flexfit.Models.User", "User")
                        .WithMany("UserWorkoutHistories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserWorko__UserI__5AB9788F");

                    b.Navigation("ClassBooking");

                    b.Navigation("GymBooking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flexfit.Models.Branch", b =>
                {
                    b.Navigation("BranchImages");

                    b.Navigation("BranchStaffs");

                    b.Navigation("Classes");

                    b.Navigation("GymSessions");
                });

            modelBuilder.Entity("Flexfit.Models.Category", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Flexfit.Models.Class", b =>
                {
                    b.Navigation("ClassBookings");

                    b.Navigation("ClassSchedules");

                    b.Navigation("FavoriteClasses");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Flexfit.Models.ClassBooking", b =>
                {
                    b.Navigation("CheckInLogs");

                    b.Navigation("UserWorkoutHistories");
                });

            modelBuilder.Entity("Flexfit.Models.CreditPackage", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Flexfit.Models.Gym", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("FavoriteGyms");

                    b.Navigation("GymImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Flexfit.Models.GymBooking", b =>
                {
                    b.Navigation("CheckInLogs");

                    b.Navigation("UserWorkoutHistories");
                });

            modelBuilder.Entity("Flexfit.Models.GymSession", b =>
                {
                    b.Navigation("GymBookings");
                });

            modelBuilder.Entity("Flexfit.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Flexfit.Models.User", b =>
                {
                    b.Navigation("BranchStaffs");

                    b.Navigation("CheckInLogScannedByNavigations");

                    b.Navigation("CheckInLogUsers");

                    b.Navigation("ClassBookingCheckedInByNavigations");

                    b.Navigation("ClassBookingUsers");

                    b.Navigation("CreditTransactions");

                    b.Navigation("FavoriteClasses");

                    b.Navigation("FavoriteGyms");

                    b.Navigation("GymBookingCheckedInByNavigations");

                    b.Navigation("GymBookingUsers");

                    b.Navigation("Gyms");

                    b.Navigation("MemberProfile");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");

                    b.Navigation("SystemLogs");

                    b.Navigation("UserCredit");

                    b.Navigation("UserRoles");

                    b.Navigation("UserWorkoutHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
