<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="NSubstitute" Version="5.1.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\FlexFit.Contracts\FlexFit.Contracts.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\FlexFit.Caching\FlexFit.Caching.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\FlexFit.RedisEventBus\FlexFit.RedisEventBus.csproj" />
    <ProjectReference Include="..\..\src\Services\Identity\FlexFit.Identity.API\FlexFit.Identity.API.csproj" />
    <ProjectReference Include="..\..\FlexFit.BookingService\FlexFit.BookingService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ApiIntegrationTests.cs" />
    <Compile Remove="ApplicationUnitTests.cs" />
    <Compile Remove="IdentityPersistenceTests.cs" />
    <Compile Remove="Phase9UnitTests.cs" />
    <Compile Remove="RedisIntegrationTests.cs" />
    <Compile Remove="SecurityUnitTests.cs" />
  </ItemGroup>

</Project>
