using FlexFit.Catalog.Repository.Data;
// <auto-generated />
using System;
using FlexFit.Catalog.Repository.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlexFit.Catalog.Repository.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BranchAmenityMapping", b =>
                {
                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BranchId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("BranchAmenityMappings", (string)null);
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.Branch", b =>
                {
                    b.Property<Guid>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreditCost")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BranchId")
                        .HasName("PK__Branches__A1682FC57F628C8E");

                    b.HasIndex("GymId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.BranchImage", b =>
                {
                    b.Property<Guid>("BranchImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchImageId")
                        .HasName("PK__BranchIm__DEDBCB2E0DD9038B");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchImages");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.BranchStaff", b =>
                {
                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("StaffId", "BranchId");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchStaffs");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0BC8C5ABA1");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__Categori__8517B2E053ED6742")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.Class", b =>
                {
                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CaloriesBurnEstimate")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CoachName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreditCost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Open");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__CB1927C00781F387");

                    b.HasIndex("BranchId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.ClassSchedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndHour")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartHour")
                        .HasColumnType("time");

                    b.HasKey("ScheduleId")
                        .HasName("PK__ClassSch__9C8A5B49CB2537F1");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassSchedules");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.FavoriteClass", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("FavoriteClasses", (string)null);
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.FavoriteGym", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "GymId");

                    b.HasIndex("GymId");

                    b.ToTable("FavoriteGyms");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.Gym", b =>
                {
                    b.Property<Guid>("GymId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GymName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GymId")
                        .HasName("PK__Gyms__1A3A7C967D8AF47B");

                    b.ToTable("Gyms");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.GymAmenity", b =>
                {
                    b.Property<Guid>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AmenityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AmenityId")
                        .HasName("PK__GymAmeni__842AF50BF3A9D836");

                    b.HasIndex(new[] { "AmenityName" }, "UQ__GymAmeni__7B4A459F1F1C7085")
                        .IsUnique();

                    b.ToTable("GymAmenities");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.GymImage", b =>
                {
                    b.Property<Guid>("GymImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GymImageId")
                        .HasName("PK__GymImage__659DCAAE6F641A53");

                    b.HasIndex("GymId");

                    b.ToTable("GymImages");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.GymSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreditCost")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Open");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionId")
                        .HasName("PK__GymSessi__C9F492905AF95180");

                    b.HasIndex("BranchId");

                    b.ToTable("GymSessions");
                });

            modelBuilder.Entity("BranchAmenityMapping", b =>
                {
                    b.HasOne("FlexFit.CatalogService.Models.GymAmenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .IsRequired()
                        .HasConstraintName("FK__BranchAme__Ameni__6E01572D");

                    b.HasOne("FlexFit.CatalogService.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__BranchAme__Branc__6D0D32F4");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.Branch", b =>
                {
                    b.HasOne("FlexFit.CatalogService.Models.Gym", "Gym")
                        .WithMany("Branches")
                        .HasForeignKey("GymId")
                        .IsRequired()
                        .HasConstraintName("FK__Branches__GymId__5812160E");

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.BranchImage", b =>
                {
                    b.HasOne("FlexFit.CatalogService.Models.Branch", "Branch")
                        .WithMany("BranchImages")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__BranchIma__Branc__66603565");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.BranchStaff", b =>
                {
                    b.HasOne("FlexFit.CatalogService.Models.Branch", "Branch")
                        .WithMany("BranchStaffs")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_BranchStaffs_Branches");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.Class", b =>
                {
                    b.HasOne("FlexFit.CatalogService.Models.Branch", "Branch")
                        .WithMany("Classes")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__Classes__BranchI__7D439ABD");

                    b.HasOne("FlexFit.CatalogService.Models.Category", "Category")
                        .WithMany("Classes")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Classes__Categor__7E37BEF6");

                    b.Navigation("Branch");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.ClassSchedule", b =>
                {
                    b.HasOne("FlexFit.CatalogService.Models.Class", "Class")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__ClassSche__Class__02084FDA");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.FavoriteClass", b =>
                {
                    b.HasOne("FlexFit.CatalogService.Models.Class", "Class")
                        .WithMany("FavoriteClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.FavoriteGym", b =>
                {
                    b.HasOne("FlexFit.CatalogService.Models.Gym", "Gym")
                        .WithMany("FavoriteGyms")
                        .HasForeignKey("GymId")
                        .IsRequired()
                        .HasConstraintName("FK__FavoriteG__GymId__4B7734FF");

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.GymImage", b =>
                {
                    b.HasOne("FlexFit.CatalogService.Models.Gym", "Gym")
                        .WithMany("GymImages")
                        .HasForeignKey("GymId")
                        .IsRequired()
                        .HasConstraintName("FK__GymImages__GymId__619B8048");

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.GymSession", b =>
                {
                    b.HasOne("FlexFit.CatalogService.Models.Branch", "Branch")
                        .WithMany("GymSessions")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__GymSessio__Branc__778AC167");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.Branch", b =>
                {
                    b.Navigation("BranchImages");

                    b.Navigation("BranchStaffs");

                    b.Navigation("Classes");

                    b.Navigation("GymSessions");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.Category", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.Class", b =>
                {
                    b.Navigation("ClassSchedules");

                    b.Navigation("FavoriteClasses");
                });

            modelBuilder.Entity("FlexFit.CatalogService.Models.Gym", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("FavoriteGyms");

                    b.Navigation("GymImages");
                });
#pragma warning restore 612, 618
        }
    }
}


